---
# COPY and this file to secrets.yml and modify as needed
development:
  SECURE_SCHEME: HTTP
  MSG_KEY: QwsjC6WdxnNYjiWn5qOFp4xBRFcWY+wjrARjV0Vz3cA=
  DB_KEY: uIlZs0Q1+/KuRWRp1HdiLeqSx62WBTZ7aIzgfSnk9r0=
  DATABASE_URL: sqlite://app/db/store/development.db
  SENDGRID_API_KEY: <provision new API key on SendGrid>
  SENDGRID_API_URL: https://api.sendgrid.com/v3/mail/send
  SENDGRID_FROM_EMAIL: <provision single sender email address on SendGrid>
  SENDGRID_API_URL: https://api.sendgrid.com/v3/mail/send

test:
  SECURE_SCHEME: HTTP
  MSG_KEY: QwsjC6WdxnNYjiWn5qOFp4xBRFcWY+wjrARjV0Vz3cA=
  DB_KEY: uIlZs0Q1+/KuRWRp1HdiLeqSx62WBTZ7aIzgfSnk9r0=
  DATABASE_URL: sqlite://app/db/store/test.db
  SENDGRID_API_KEY: <provision new API key on SendGrid>
  SENDGRID_API_URL: https://api.sendgrid.com/v3/mail/send
  SENDGRID_FROM_EMAIL: <provision single sender email address on SendGrid>
  SENDGRID_API_URL: https://api.sendgrid.com/v3/mail/send

production:
  SECURE_SCHEME: HTTPS
  DB_KEY: <`rake newkey:db`>
  MSG_KEY: <`rake newkey:msg`>
  DATABASE_URL: <do not set - allow service provider to set>
  SENDGRID_API_KEY: <provision new API key on SendGrid>
  SENDGRID_API_URL: https://api.sendgrid.com/v3/mail/send
  SENDGRID_FROM_EMAIL: <provision single sender email address on SendGrid>
  SENDGRID_API_URL: https://api.sendgrid.com/v3/mail/send